@startuml farmacia_use_case

left to right direction

actor Funcionario as f
actor Sistema as s
actor Gerente as g

rectangle "Gerenciar Clientes" {
  f --> (Cadastrar Cliente)
  f --> (Atualizar Cliente)
  f --> (Realizar Compra)
  f --> (Realizar Login)
  f --> (Alterar Senha)
}

rectangle "Gerenciar Funcionários" {
  g --> (Cadastrar Funcionário)
  g --> (Atualizar Funcionário)
}

rectangle "Gerenciar Compras" {
  f --> (Realizar Venda)
  f --> (Realizar Devolução)
}

rectangle "Gerenciar Estoque" {
  f --> (Adicionar Produto no Estoque)
  f --> (Remover Produto do Estoque)
  f --> (Consultar Produto no Estoque)
  f --> (Listar Produtos no Estoque)
  s --> (Gerar Relatório de Estoque)
  s --> (Gerar Relatório de Produto)
  s --> (Notificação de Estoque Baixo)
}

rectangle "Gerenciar Produtos" {
  g --> (Cadastrar Produto)
  g --> (Atualizar Produto)
}

f <|-- g

@enduml
