# Generated by Django 4.2.5 on 2023-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDRFarmacia', '0003_cliente_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('precoVenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precoCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidadeEmEstoque', models.PositiveIntegerField()),
                ('fabricante', models.CharField(max_length=255)),
                ('fornecedor', models.CharField(max_length=255)),
            ],
        ),
    ]
